---
title: "forest-snow-fire-manuscript"
output: word_document
date: "2023-03-20"
geometry: margin=1.0in
font-size: 12pt
editor_options: 
  markdown: 
    wrap: 100
bibliography: myrefs1.bib
csl: philtransrscb.csl
header-includes:
    - \usepackage{setspace}\doublespacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

**The one question is**: Climate warming is expected to increase fire severity, while reducing
snowfall, and causing earlier snowmelt and lengthening summer drought and fire season duration. To
date, the relationship between snow cover dynamics and wildfire severity remains uncertain.

**Here we do**: We used structural equation modelling to test a hypothesized causal structure
between stand structure, snow cover dynamics, and burn severity for 689 fires that burn in the
boreal forest of Ontario between 2002-2019. 

**What we found**: We found that the relationship between stand structure and burn severity was
strongly mediated by snow cover, and that the strength of the relationships differed across spatial
and temporal scales.

**How it matters**:

# Introduction

# Methods

*Study Area*

Our study was focused on the boreal shield ecoregion of Ontario.

Between 2008 and 2018, over a third of the wildfires that burned in the boreal forest of Canada
occurred in the Ontario's boreal shield ecoregion [@coops.etal2018].

*Data*

**raw data**

Wildfires occurrence and polygon data were obtained for the years 2002 to 2019 from the Fire
Disturbance Area database created and openly distributed by the government of Ontario. We excluded
all fires that were classified as prescribed burns in the database. Fires that burn through a
previously burnt area, referred to as reburns, may burn more or less severely than fires that burnt
in areas without recent history of previous wildfire [@whitman.etal2019]. Therefore, we excluded all
reburns in our data following preexisting protocol outlined in [@whitman.etal2022]. Fires were
removed if the overlap between polygons were greater than the smallest area burned in our dataset
(40ha) and the gap between the fires was equal to or less than 26 years. We chose 26 years because
that represents the earliest year in which we had fire perimeter data for the first fire in our
dataset. After filtering out prescribed fires and reburns we had a total of 710 fires that burned
during 2002-2019.

**data processing**

Remotely sensed burn severity maps were obtained from Google Earth Engine (GEE) at a 30m spatial
resolution based on fire perimeters for wildfires that burned between 2002-2019. Burn severity was
measured using the relativized burn ratio (RBR). RBR is a Landsat-based fire severity metric that
represents the change in forest cover following a fire relative to the amount of pre-fire vegetative
cover rather than the absolute change. RBR is a more robust measure of burn severity comparing to
other Landsat-based approaches (e.g., rNBR) as it is more sensitive to pre-fire values
[@parks.etal2014]. Burn severity maps were generated from Landsat TM, ETM+ and OLI imagery following
a hybrid mean-compositing approach developed for the boreal region [@holsinger.etal2021] that
calculates the mean across a stack of pre-fire and post-fire imagery (see supplementary materials).

To determine snow free date we used the global, 500-m resolution, daily snow cover product, version
6 from NASA's Moderate Resolution SpectroRadiometer (MODIS/Terra MOD10A1) to generate maps in GEE
for each fire perimeter using an algorithm developed for the northern hemisphere [@. SDD is the last
date that snow is detected in a pixel, calculated as the longest period without snow after a minimum
of 5 days of snow cover (150). Maps were produced for the entire extent of the Ontario boreal
shield. We then calculated the mean SDD across each fire event to produce and estimate of SDD for
each event. To produce an estimate of time since snowmelt we calculated mean SDD for each fire
perimeter and then mean fire burn date across the fire perimeter prior to calculating the difference
between mean fire burn date and SDD. Mean fire burn date was calculated as the julian day of
ignition average across the entire perimeter and was determined by modifying a previous algorithm
developed in GEE based on MODIS Terra and Aqua Thermal Anomalies and Fire Daily Global datasets
(MOD14A1 V6 and MYD14A1) to calculate the day that a fire stopped burning (104).

**structural equation modellin**g

# Results

*Ontario boreal shield*

Across our entire study region, our structural equation model fit the data well with based on
good-of-fit static for both burn severity extremes (*C* = 14.177, *df* = 8 , *p* = 0.077) and median
burn severity (*C* = 14.177, *df* = 8 , *p* = 0.077) and revealed both direct and indirect
relationships between forest structural diversity, snow cover dynamics and burn severity. Our models
of median burn severity and burn severity extremes explained a high proportion of variance in both
snow free date *R*~2~ = 0.67 and snow free duration *R*~2~ = 0.84. Our models expalined a higher
proportion of variance in burn severity extremes *R*~2~ = 0.20 relative to our models of median burn
severity *R*~2~ = 0.12.

We found a significant and negative direct relationship between total aboveground biomass and snow
free date (fig 1a., Table 1). Stand age had a significant but positive direct relationship on snow
free date (fig 1a, Table 1). We did not find a significant relationship between percent canopy
closure and snow free date (fig 1a, Table 1). Topography, represented by terrain ruggedness index,
had a significant and negative direct relationship on snow free date (fig 1a, Table 1). We found a
significant but negative direct relationship of snow free date on snow free duration (fig 1a, Table
1). We found significant but positive direct relationships of both drought and stand age on snow
free duration, with a stronger direct relationship between drought and snow free duration (fig 1a,
Table 1). Drought and snow free duration had significant direct relationships on median burn
severity and burn severity extremes (fig 1a, Table 1). Drought had a negative relationship with burn
severity extremes but a positive relationship with median burn severity (fig 1a, Table 1). The
relationship between snow free duration and median burn severity was negative whereas the
relationship between burn severity extremes and snow free duration was positive (fig 1a, Table 1).
All forest structure metrics had no significant direct relationship with median burn severity but
all metrics had a significant direct relationship with burn severity extremes (Table 1). Stand age
and canopy closure had a negative relationship with burn severity extremes whereas total aboveground
biomass have a positive relationship (fig1a).

The indirect relationship between forest structural diversity and median burn severity - calculated
by multiplying the standardized regression coefficients of the path coefficients - showed that the
effects of stand age were stronger than canopy closure but similar to that of total aboveground
biomass, although stand age was positive whereas biomass was negative (fig 1b). In contrast, the
direct effect of canopy closure on median burn severity is stronger than both stand age and total
aboveground biomass, both of which had relatively low direct effects (fig 1b). More importantly, the
total causal effects of total aboveground biomass and canopy closure were similar and much strong
than stand age (fig 1b).

The indirect effects of forest structural diversity on burn severity extremes were strongest for
stand age compare to both total aboveground biomass and canopy closure (fig 1a). The indirect
relationships for canopy closure and total aboveground biomass were positive whereas stand age had a
negative indirect relationship with burn severity extremes. Critically, the total causal effects of
total aboveground biomass were stronger compared to both stand age and canopy closure (fig 1a).
Total aboveground biomass and canopy closure had positive indirect relationships and stand age had a
negative indirect relationship.

The indirect relationship of drought were strongest for burn severity extremes compared to median
burn severity. Yet, drought had an indirect positive relationship with burn severity extremes and
indirect negative relationship for median burn severity (fig1a, fig1b). The total cause effects of
drought were positive. In contrast, topography had a positive indirect relationship with both median
burn severity and burn severity extremes, yet these relationships were weaker than drought. However,
because the indirect relationship of drought on burn median burn severity was strongly negative and
the direct relationship was strongly positive, the strength and direction of these effects cancel
each other out and the total causal effects of drought on median burn severity to be weaker than
topography (fig 1b).

*East vs. West Ontario*

For western Ontario, our structural equation model fit the data better compared to the models for
all of Ontario based on the goodness-of-fit statistic for both burn severity extremes (*C* = 9.864,
*df* = 10, *p* = 0.453) and median burn severity (*C* = 9.864, *df* = 10, *p* = 0.453) .

# Discussion
