---
title: "clean_climNA_data"
author: "Jack Goldman"
date: "2023-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/jandr/Documents/PhD/Thesis/")

```

```{r}

clim_data <-  read.csv("OntBSdb/Climate/On_Fire_Elevation_1980-2020M.csv")

clim_data$ID1 <- str_remove(clim_data$ID1, "_rbr") # remove rbr at the end of id

```



```{r}
clim_data_v1 <- 
  clim_data %>% 
  #filter(Year >= 2001) %>% # filter out climate data from years before 2001
  rename(Fire_ID = "ID1") %>% # rename ID1 column to fireID
  semi_join(df_snow, by = "Fire_ID") %>%
  left_join(df_snow, by = "Fire_ID") %>%  # filter out fires that did no burn btw 01-2020
  select(-c(ID2, Longitude, Latitude, Elevation)) %>% # remove unnecessary columns
  mutate(fire_month = month(ymd(Fire_Start)), .after = Fire_Year, #get the mont that the fire burned # not necessary
         fire_julday = yday(ymd(Fire_Start))) %>%  # get julday for calendar year calculation
  rename_all(tolower) %>% 
  select(c(year:fire_id,fire_year:tssm, tave01:tave12, cmi01:cmi12, rh01:rh12, ppt01:ppt12)) %>% # select important variables
  mutate(matches = case_when(
    year == fire_year ~ "yes",
    TRUE ~ "no")) %>% # create matches for the years we need
  filter(matches == "yes") %>% 
  select(-c(matches, year)) %>% 
  separate(snow_melt,  c("sdd_y", "sdd_m", "sdd_d"), "-") %>%
    separate(fire_start,  c("f_y", "f_m", "f_d"), "-") %>% 
  select(-c(f_y, f_d, sdd_y, sdd_d,fire_month, fire_julday)) 
  


```


## lets calculate climate from time since snowmelt to fire month

```{r calculate average climate variables between sdd month and fire month}
#create empty dataframe
df_fullclim <-  setNames(data.frame(matrix(ncol = 4, nrow = 0)), c("fireID", "avg_cmi", "avg_ppt", "avg_vpd"))

#load the vpd calc function

source("SnowVariability_BurnSeverity/scripts/vpd_function.R")

#loop that calculates avg cmi, ppt and vpd
for (i in 1:nrow(clim_data_v1)) {
  #read in data
  clim <-  clim_data_v1[i,] 
  
  #cmi calc
  cmi_v1 <-  clim %>%  select(c(starts_with("cmi"), sdd_m, f_m, fire_id))
  sdd_code <- cmi_v1$sdd_m
  f_code <- cmi_v1$f_m
  to_match <- c(sdd_code:f_code)
  nums <- cmi_v1[,names(cmi_v1) %in% colnames(cmi_v1)[grepl(paste(to_match,collapse="|"),colnames(cmi_v1))]]
  results <- lapply(nums,as.numeric)
  nums <- as.data.frame(do.call(cbind, results))
  avg_nums <- nums %>% mutate(avg = rowMeans(nums)) %>%  select(avg)
  avg_nums <- round(avg_nums, digits = 2)
  
  #ppt calc
  ppt_v1 <-  clim %>%  select(c(starts_with("ppt"), sdd_m, f_m, fire_id))
  sdd_code_p <- ppt_v1$sdd_m
  f_code_p <- ppt_v1$f_m
  to_match_p <- c(sdd_code_p:f_code_p)
  nums_p <- ppt_v1[,names(ppt_v1) %in% colnames(ppt_v1)[grepl(paste(to_match_p,collapse="|"),colnames(ppt_v1))]]
  results_p <- lapply(nums_p,as.numeric)
  nums_p <- as.data.frame(do.call(cbind, results_p))
  avg_nums_p <- nums_p %>% mutate(avg = rowMeans(nums_p)) %>%  select(avg)
  avg_nums_p <- round(avg_nums_p, digits = 2)
  
  #vpd calc
  tave_v1 <-  clim %>%  select(c(starts_with("tave"), sdd_m, f_m, fire_id))
  rh_v1 <-  clim %>%  select(c(starts_with("rh"), sdd_m, f_m, fire_id))

  sdd_code_t <- tave_v1$sdd_m
  f_code_t <- tave_v1$f_m
  to_match_t <- c(sdd_code_t:f_code_t)
  sdd_code_r <- rh_v1$sdd_m
  f_code_r <- rh_v1$f_m
  to_match_r <- c(sdd_code_r:f_code_r)
  
  nums_t <- tave_v1[,names(tave_v1) %in% colnames(tave_v1)[grepl(paste(to_match_t,collapse="|"),colnames(tave_v1))]]
  nums_r <- rh_v1[,names(rh_v1) %in% colnames(rh_v1)[grepl(paste(to_match_r,collapse="|"),colnames(rh_v1))]]
 
  results_t <- lapply(nums_t,as.numeric)
  results_r <- lapply(nums_r,as.numeric)

  
  nums_vpd_1 <- as.data.frame(do.call(rbind, results_t)) # i need to cbind so two columns one with tave and one with rh
  nums_vpd_2 <- as.data.frame(do.call(rbind, results_r)) # i need to cbind so two columns one with tave and one with rh
  nums_vpd <-  cbind(nums_vpd_2, nums_vpd_1)
  colnames(nums_vpd) <- c("rh", "tave")
  
  avg_vpd_pm <- nums_vpd %>% 
    mutate(vpd_m = vpd(rh, tave)) %>% 
    select(-c(rh, tave)) %>% 
    rownames_to_column("month") %>% 
    pivot_wider(names_from = month, 
                values_from = vpd_m) 
  
  avg_vpd <- avg_vpd_pm %>% mutate(avg_vpd = rowMeans(avg_vpd_pm)) %>% select(avg_vpd)
  
  #dataframe combine
  clim_v2 <- clim %>% select(fire_id) %>% rename(Fire_ID = "fire_id")
  colnames(avg_nums) <- c("avg_cmi")
  colnames(avg_nums_p) <- c("avg_ppt")
  input <- cbind(clim_v2, avg_nums, avg_nums_p, avg_vpd)
  new <- rep(input, ncol(df_fullclim)) 
  df_fullclim[nrow(df_fullclim) + 1, ] <- new  
}

rm(avg_nums, avg_nums_p, avg_vpd, avg_vpd_pm, clim, clim_data, clim_data_v1, clim_v2, cmi_v1, df_climavgs, input, nums, new, nums_p, nums_r, nums_t, nums_vpd, nums_vpd_1, nums_vpd_2, ppt_v1, results_t, results_r, results_p, rh_v1, tave_v1)
```
save it
```{r}
#remove ppt - not used from climate NA
df_fullclim <- df_fullclim %>% 
   select(-c(avg_ppt)) %>% 
  rename(Fire_ID = "fireID")

write.csv(df_fullclim, "SnowVariability_BurnSeverity/Data/monthly_cmi_vpd_ClimNA_01_2020.csv")
```

