---
title: "east-west-sem"
author: "Jack A Goldman"
date: "2023-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/jgoldman/Work/PhD/forest-snow-fire-interactions/")

```


## Data analysis for structural equation Model

Load packages

```{r}
library(piecewiseSEM)
library(nlme)
library(tidyverse)
library(kableExtra)
source("scripts//sem-table-function.R")
```

Read in data
```{r}
df_snow <- read.csv("Data/0-forest-snow-fire-data.csv") %>% 
  filter(Fire_Year < 2020 | Fire_Year <=2001) 

#where are nas
nas <-  df_snow %>% 
  select_if(function(x) any(is.na(x))) #ecoregion na's

#omit na's
new_data <- df_snow %>% select(-c(ecoregion)) %>% na.omit(.)

#make sure DC is greater than 0
new_data <- new_data %>% filter( dc > 0) 



```

Transform the rbr quant
```{r}
new_data <- new_data %>% mutate(rbr_qs = sqrt((max(RBR_quant+1)-RBR_quant)))

```

Divide into east and west
```{r}
#east vs. west
new_data_w <- new_data %>% filter(pyroregion == 1)
new_data_e <- new_data %>% filter(pyroregion == 0)
```


## Western Boreal Shield of Ontario

```{r}
hist(new_data_w$rbr_qs) # ok 
hist(new_data_w$RBR_median) # ok
```

Calculate the free model for western boreal shield of Ontario
```{r, Extreme Burn Severity Western Boreal Shield Of Ontario}
new_data_w1 = new_data_w %>% mutate(dc= c(scale(dc)),
                                    tssm = c(scale(tssm)),
                                    sdd = c(scale(sdd)),
                                    tri = c(scale(tri)),
                                    age = c(scale(age)),
                                    avgbio = c(scale(avgBio)))
#removed topography and age effects of SFDR which were not in our hypothesized dag originally
#and got a good fishers C
west_sem_ext <- psem(
  lme(sdd ~  avgBio + age + cc+ tri, random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_w, method = "ML"),
  lme(tssm ~ sdd +  + dc   , random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_w, method = "ML"),
   lme(rbr_qs ~ dc + tssm + sdd +tri +age + 
        avgBio + cc , random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_w, method = "ML")
)

#summary
summary(west_sem_ext)

#examine plots
lapply(west_sem_ext, function(i) hist(resid(i))) # looks generally normal

```


```{r, summary table for west extreme} 
#tidy table

modsum_west_ext <- sem_table(west_sem_ext, region = "w")

modsum_west_ext

write.csv(modsum_west_ext, "results/results-summary-tables/Table-3-sem-ext-west.csv")

```










```{r, west med}

#also removed topography and age from the TSSM in our dag
west_sem_med <- psem(
 lme(sdd ~  avgBio + age + cc+ tri, random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_w, method = "ML"),
  lme(tssm ~ sdd +  dc  , random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_w, method = "ML"),
   lme(RBR_median ~ dc + tssm + sdd +tri +age + 
        avgBio + cc , random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_w, method = "ML")
)

#summary
summary(west_sem_med)

#examine plots
lapply(west_sem_med, function(i) hist(resid(i))) # looks generally normal

#
#tidy table

 
modsum_west_med <- sem_table(west_sem_med, region = "w")



modsum_west_med 
write.csv(modsum_west_med, "results/results-summary-tables/Table-4-sem-med-west.csv")

```

## Eastern boreal shield

```{r}
hist(new_data_e$RBR_median)# ok
hist(new_data_e$rbr_qs) # seems ok but there is a funky tail situation going on.
```


Eastern boreal shield extreme
```{r}
#added age as a causal parent of SFDR  (TSSM) because they are not conditionally independent... However
# the fischer c-statistic was still very high. Therefore I should probably think about this
# p-value was equal to 0.005
east_sem_ext <- psem(
  lme(sdd ~  avgBio + age + cc+ tri, random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_e, method = "ML"),
  lme(tssm ~ sdd +  dc  , random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_e, method = "ML"),
   lme(rbr_qs ~ dc + tssm + sdd +tri +age + 
        avgBio + cc , random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_e, method = "ML")
)

#cc may be better than avgBio here
#summary
summary(east_sem_ext)

###### looks like we have  an independence claim
#tssm ~ age - this is different from the west model and the full model



#examine plots
plot(east_sem_ext)
lapply(east_sem_ext, function(i) hist(resid(i))) # looks generally norma

#
#tidy table
modsum_ee <- sem_table(east_sem_ext, region = "e")



modsum_ee

write.csv(modsum_ee, "results/results-summary-tables/Table-5-sem-ext-east.csv")

```

### East SEM - med

```{r}

#same thing with age and SFDR as above. left out of model
east_sem_med <- psem(
  lme(sdd ~  avgBio + age + cc+ tri, random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_e, method = "ML"),
  
  lme(tssm ~ sdd + dc  , random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_e, method = "ML"),
  
  lme(RBR_median ~ dc + tssm + sdd +tri +age + 
        avgBio + cc, random = ~1 | Fire_Year/size_class, na.action = na.omit, data = new_data_e, method = "ML")
)

#summary
summary(east_sem_med)

#examine plots
lapply(east_sem_med, function(i) hist(resid(i))) # looks generally normal

#
#tidy table
#tidy table
modsum_em <- sem_table(east_sem_med, region = "e")

modsum <- summary(east_sem_med)$coefficients
modsum$Estimate <- round(modsum$Estimate, 3)
modsum$Std.Error <- round(modsum$Std.Error, 3)
modsum$Crit.Value <- round(modsum$Crit.Value, 3)
modsum$P.Value <- round(modsum$P.Value, 3)
modsum$P.Value <- ifelse(modsum$P.Value<0.001, "<0.001", modsum$P.Value)
modsum$Std.Estimate <- round(modsum$Std.Estimate, 3)
modsum$Response <- gsub("_", " ", modsum$Response)
modsum$Predictor <- gsub("_", " ", modsum$Predictor)
colnames(modsum)[4:8] <- c("SE", "DF", "t-Value", "P-Value", "Std. Estimate")
modsum <- data.frame(modsum)


modsum_em
write.csv(modsum_em, "results/results-summary-tables/Table-6-sem-med-east.csv")

```

# indirect effects

```{r}
source("./scripts//indirect-effects-function.R")
source("./scripts/total-effects-function.R")
source("./scripts/pathway-plot-function.R")
```

# east sem ext
```{r}

#indirect
east_ext_ont_ind_effects <- ind.eff(east_sem_ext, response = "extreme")
east_ext_ont_ind_effects 
<- #specific
east_ext_ont_spec_ind_eff <- spec.ind.eff(east_sem_ext, response = "extreme")
east_ext_ont_spec_ind_eff
#total
east_ext_ont_tot_effects <- tot.eff(east_sem_ext, response = "extreme")
east_ext_ont_tot_effects

#pathway plot
east_ext_pathway <- pathway.plot(east_ext_ont_ind_effects, east_ext_ont_tot_effects, response = "extreme", region = "east")

east_ext_pathway
```


# east sem med
```{r}
#
east_med_ont_ind_effects <- ind.eff(east_sem_med, response = "median")
east_med_ont_ind_effects 
#specific
east_med_ont_spec_ind_eff <- spec.ind.eff(east_sem_med, response = "median")
east_med_ont_spec_ind_eff
#total
east_med_ont_tot_effects <- tot.eff(east_sem_med, response = "median")
east_med_ont_tot_effects

#pathway plot
east_med_pathway <- pathway.plot(east_med_ont_ind_effects, east_med_ont_tot_effects, response = "median", region = "east")

east_med_pathway

```

# west sem ext

```{r}
#indirect
west_ext_ont_ind_effects <- ind.eff(west_sem_ext, response = "extreme")
west_ext_ont_ind_effects 
#specific
west_ext_ont_spec_ind_eff <- spec.ind.eff(west_sem_ext, response = "extreme")
west_ext_ont_spec_ind_eff
#total
west_ext_ont_tot_effects <- tot.eff(west_sem_ext, response = "extreme")
west_ext_ont_tot_effects

#pathway plot
west_ext_pathway <- pathway.plot(west_ext_ont_ind_effects, west_ext_ont_tot_effects, response = "extreme", region = "west")
west_ext_pathway
```

# west sem med
```{r}
west_med_ont_ind_effects <- ind.eff(west_sem_med, response = "median")
west_med_ont_ind_effects 
#specific
west_med_ont_spec_ind_eff <- spec.ind.eff(west_sem_med, response = "median")
west_med_ont_spec_ind_eff
#total
west_med_ont_tot_effects <- tot.eff(west_sem_med, response = "median")
west_med_ont_tot_effects

#pathway plot
west_med_pathway <- pathway.plot(west_med_ont_ind_effects, west_med_ont_tot_effects, response = "median", region = "west")

west_med_pathway 
```
```{r}
library(patchwork)

grouped_path(west_ext_pathway, east_ext_pathway,  west_med_pathway , east_med_pathway) 

ggsave("~/Desktop/OneDrive - University of Toronto/Projects/forest-snow-fire-interactions/figures-tables/figures/FigureS2-east-west-ind-effects.png", width = 20, height = 20, units = "cm")
```

